# Generated by Django 5.1.1 on 2024-09-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchasemaster_purchasesupplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedetails',
            name='UserId',
        ),
        migrations.RemoveField(
            model_name='purchasemaster',
            name='UserId',
        ),
    ]
