# Generated by Django 5.1.1 on 2024-09-09 05:53

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemId', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=30)),
                ('ItemRate', models.IntegerField()),
                ('Itemstatus', models.BooleanField(default=True)),
                ('ItemEntryDate', models.DateField(default=datetime.date.today)),
                ('UserId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'db_table': 'tbl_item_mstr',
            },
        ),
    ]
