# Generated by Django 5.1.1 on 2024-09-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_itementrydate_alter_item_itemname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Itemstatus',
            field=models.IntegerField(default=1),
        ),
    ]
