# Generated by Django 5.1.1 on 2024-09-16 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('userName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('entryDate', models.DateField(default=django.utils.timezone.now)),
                ('userStatus', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
    ]
