# Generated by Django 5.1.1 on 2024-09-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usersession'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersession',
            table='tbl_session',
        ),
    ]
