# Generated by Django 5.1.1 on 2024-09-10 10:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0003_remove_purchasedetails_userid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMaster',
            fields=[
                ('SalesMasterId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=30)),
                ('CustomerPhone', models.CharField(max_length=30, unique=True)),
                ('SalesMasterReference', models.CharField(max_length=30, unique=True)),
                ('SalesDate', models.DateField(blank=True, null=True)),
                ('SalesMasterEntryDate', models.DateField(default=django.utils.timezone.now)),
                ('SalesMasterTotal', models.CharField(max_length=30)),
                ('SalesMasterstatus', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tbl_sales_mstr',
            },
        ),
        migrations.CreateModel(
            name='SalesDetails',
            fields=[
                ('SalesDetailId', models.AutoField(primary_key=True, serialize=False)),
                ('ItemQuantity', models.IntegerField()),
                ('ItemPrice', models.IntegerField()),
                ('ItemAmount', models.CharField()),
                ('SalesDetailEntryDate', models.DateField(default=django.utils.timezone.now)),
                ('SalesDetailsstatus', models.IntegerField(default=1)),
                ('ItemAssigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchasedetails')),
                ('SalesMasterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesmaster')),
            ],
            options={
                'db_table': 'tbl_purchse_dtl',
            },
        ),
    ]
