# Generated by Django 5.1.1 on 2024-09-10 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_itemstatus'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdetails',
            name='ItemAssigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AlterModelTable(
            name='salesdetails',
            table='tbl_sales_dtl',
        ),
    ]
