# Generated by Django 5.1.1 on 2024-09-11 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_remove_purchasedetails_userid_and_more'),
        ('sales', '0002_alter_salesdetails_itemassigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdetails',
            name='ItemAssigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchasedetails'),
        ),
    ]
