# Generated by Django 5.1.1 on 2024-09-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_salesdetails_itemassigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmaster',
            name='CustomerPhone',
            field=models.CharField(max_length=30),
        ),
    ]
